# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 12:29
from __future__ import unicode_literals

import campaign.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_list_name', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(upload_to=campaign.models.get_maillistFile_path)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50, unique=True)),
                ('template_image', models.ImageField(upload_to=campaign.models.get_templatesimage_path)),
                ('file', models.FileField(upload_to=campaign.models.get_templatesfile_path)),
                ('category', models.CharField(choices=[('PROMOTIONAL', 'promotional'), ('ADVERTISEMENT', 'advertisement'), ('SOCIAL', 'social'), ('OTHER', 'others')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mail_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.MailingList')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
