# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_template_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='mail_list_name',
            field=models.CharField(max_length=50),
        ),
    ]
