# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_email', models.IntegerField(default=0)),
                ('remaining_email', models.IntegerField(default=0)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('package', models.CharField(choices=[('BASIC', 'basic'), ('STANDARD', 'standard'), ('ADVANCE', 'advance')], default='BASIC', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
